[package]
name = "arm-vm"
version = "0.1.0"
authors = ["kyhorne <me@kyhorne.com>"]
edition = "2018"

[dependencies]
strum = "0.13.0"
strum_macros = "0.13.0"
num-derive = "0.2.4"
num-traits = "0.2.6"
clap = "2.32.0"
